### ISSUE TITLE
Docker Compose Attempt / Slack bot config troubles

### ISSUE THREAD

**Issue by gorfreed** [zozs/a-wild-button-appears#16]
Hi Raman!

I wish I could let this loose on my unexpecting notoriously absent bunch on my Slack. I am failing on two aspects in the installation process though, probably mainly because I have little knowledge about creating bots and even less about Node.

I know Docker though so I tried your compose script. It sets up Mongo fine but in the end starts complaining about a missing node schedule module and doesnt start. I managed to install that but then the compose script will start in serverless mode, print occasional connection errors with Mongo ...

`Failed to register interactive. Got error: SyntaxError: Unexpected token u in JSON at position 0, in JSON: {}
Failed to perform hourly check, got error: MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo in JSON: {"name":"MongoServerSe                                                           lectionError","reason":{"type":"Single","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"comp                                                           `         
...or fails to connect when / commanded on Slack...

`Slackbot /wildbutton failed with the error "dispatch_failed"`                 

I am pretty sure I missed somethin setup, as you write only "Configure slash commands with the URL" in your setup guide, but not which slash commands actually are usable.

I tried running the node script locally with the Docker mongoDB but wasnt successful with that either.

Since the issues are plentiful as you see I just wanted to ask you if you would consider reworking your compose script so it runs reliably out of the box or provide some more details about the steps in between you omitted (most likely they are super pedestrian for anybody else on Github ;)

Really love the idea and enjoyed reading about your motivations behind it. 

Greetings from Berlin,
Daniel

**Comment by zozs** [comment]
Hi there future button-clicker, aka Daniel!

Sorry to hear your installation process was anything less than :100:, although you are probably the first one except me to install it, so it is not entirely unexpected :slightly_smiling_face:.

I will have to look more at that error, I'm not exactly sure what it means. However, the Dockerfile in this project is not really meant for deployment, just for some internal testing. To be honest, I'm not even sure if `serverless offline`, which the development Dockerfile is using, is safe to expose to the Internet, so that might be worth considering.

However, I actually have public distribution activated on the app, together with a cloud-hosted version that I use in a couple of workspaces I'm a member of. I have just forgotten to link to the "Add to Slack" button in the README. But that is fixed now, so please take a look at the button there. Or right below. As you might have guessed, I'm no stranger to adding buttons everywhere!

<a href="https://slack.com/oauth/v2/authorize?client_id=398308658001.1314237615088&scope=commands,channels:read,chat:write,groups:read,im:write,channels:join,chat:write.public&user_scope="><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcSet="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>

While I agree that it should be possible to self-host wildbutton, I'm afraid it might take some time before I have time to debug and document things properly, especially since I use the serverless version myself, and not the standalone one which would be required for a docker-compose solution. I'll keep this issue open though, so that can revisit it when I have some spare time!

Take care,
Linus

**Comment by gorfreed** [comment]
Thank you so much for that button, Linus! I was able to got wildbutton going right away, with some very eager users unable to resist pushing it already! :D Are there any details on what randomizer you have applied here or the frequency of its occurence?

**Comment by gorfreed** [comment]
And just a quick suggestion: It would be awesome to have wildbutton announce the scoreboard publicly once in a while. I think /wildbutton stats is private only, so its not possible to rile up (and hopefully motivate) your rival by passive-aggressively posting the current high-score :)

**Comment by zozs** [comment]
> Thank you so much for that button, Linus! I was able to got wildbutton going right away, with some very eager users unable to resist pushing it already! 

Glad to hear this :). Keep them button presses coming! :computer_mouse: 

> Are there any details on what randomizer you have applied here or the frequency of its occurence?

Sure! The button will appear on those weekdays you have selected (by default Monday through Friday). It will only be _one_ button every day (wildbutton is a big supporter of a healthy work-life balance, you can't go around waiting for buttons constantly!). The time it will appear is drawn from a uniform distribution between the hours you have selected, so if you have selected a time range between say 9-16, it will appear sometime during that interval, with equal probability for every time.

> And just a quick suggestion: It would be awesome to have wildbutton announce the scoreboard publicly once in a while. I think /wildbutton stats is private only, so its not possible to rile up (and hopefully motivate) your rival by passive-aggressively posting the current high-score :)

That's a nice idea! :+1:
